services:
  - type: web
    name: pharmacy-request-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node serveur.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        value: mongodb+srv://user:user@cluster83783.o4fhg.mongodb.net/pharmacy?retryWrites=true&w=majority&appName=Cluster83783

  - type: static
    name: pharmacy-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://pharmacy-backend-cyq7.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 